"""
Reads the 10 dubai_offices_part_XX.xlsx files in dubai_brokers_output/ and
writes www/dubai_brokers_data.js containing a single JS array (DUBAI_BROKERS_DATA)
with every broker's data. No database involved - the JS file is loaded directly
by brokers-directory.html via a <script> tag.
"""
import json
import glob
import sys
import openpyxl

sys.stdout.reconfigure(encoding="utf-8")

SOURCE_DIR = "dubai_brokers_output"
OUTPUT_FILE = "www/dubai_brokers_data.js"

EXPECTED_HEADER = (
    "#", "اللوجو", "اسم المكتب (عربي)", "اسم المكتب (إنجليزي)", "الترخيص",
    "التصنيف", "الهاتف", "البريد الإلكتروني", "الموقع الإلكتروني",
    "اسم المسؤول", "الأنشطة",
)


def clean(value):
    if value is None:
        return ""
    return str(value).strip()


def load_file(path):
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    ws = wb.active
    rows = ws.iter_rows(values_only=True)
    header = next(rows)
    if header != EXPECTED_HEADER:
        raise ValueError(f"{path}: unexpected header {header}")

    brokers = []
    for row in rows:
        if row is None or all(v is None for v in row):
            continue
        (_, logo, name_ar, name_en, license_no, rank, phone, email,
         website, manager, activities) = row[:11]

        activities_list = [a.strip() for a in clean(activities).split(",") if a.strip()]

        brokers.append({
            "name_ar": clean(name_ar),
            "name_en": clean(name_en),
            "license": clean(license_no),
            "rank": clean(rank).upper() or "GENERAL",
            "phone": clean(phone),
            "email": clean(email),
            "website": clean(website),
            "manager": clean(manager),
            "activities": activities_list,
            "logo": clean(logo),
        })
    wb.close()
    return brokers


def main():
    files = sorted(glob.glob(f"{SOURCE_DIR}/dubai_offices_part_*.xlsx"))
    if not files:
        raise SystemExit(f"No files found matching {SOURCE_DIR}/dubai_offices_part_*.xlsx")

    all_brokers = []
    for path in files:
        brokers = load_file(path)
        print(f"{path}: {len(brokers)} brokers")
        all_brokers.extend(brokers)

    for i, b in enumerate(all_brokers, start=1):
        b["id"] = i

    print(f"TOTAL: {len(all_brokers)} brokers")

    pretty_payload = json.dumps(all_brokers, ensure_ascii=False, indent=2)
    payload = json.dumps(all_brokers, ensure_ascii=False, separators=(",", ":"))

    size_before_mb = len(pretty_payload.encode("utf-8")) / (1024 * 1024)
    size_after_mb = len(payload.encode("utf-8")) / (1024 * 1024)
    print(f"الحجم قبل: {size_before_mb:.1f} MB | بعد: {size_after_mb:.1f} MB")

    js_content = (
        f"const DUBAI_BROKERS_DATA = {payload};\n\n"
        "if (typeof module !== 'undefined') module.exports = DUBAI_BROKERS_DATA;\n"
    )
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by convert_to_js.py - do not edit by hand.\n")
        f.write(js_content)

    print(f"Wrote {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
